# External input clock: 30 MHz
# Period = 1 / 30 MHz = 33.333333 ns
create_clock -name CLKIN_30M \
    -period 33.333333 \
    -waveform {0.000000 16.666667} \
    [get_ports {CLKIN}]

# Automatically create clocks generated by the ALTPLL,
# including the 128 MHz clock derived from CLKIN.
derive_pll_clocks

# Automatically calculate clock uncertainty for timing analysis.
derive_clock_uncertainty
