set_location_assignment PIN_G1  -to CLKIN

#PLC
set_location_assignment PIN_J3  -to   F_PLCI
set_location_assignment PIN_J4  -to   F_PLCO

#LED
set_location_assignment PIN_D1  -to   F_LED0
set_location_assignment PIN_E2  -to   F_LED1

#AD
set_location_assignment PIN_C3   -to  AD1_RES
set_location_assignment PIN_D2   -to  AD1_CS
set_location_assignment PIN_C2   -to  AD1_RD
set_location_assignment PIN_E3   -to  AD1_CONV
set_location_assignment PIN_E4   -to  OS1_0
set_location_assignment PIN_C4   -to  OS1_1
set_location_assignment PIN_F2   -to  OS1_2
set_location_assignment PIN_E6   -to  AD2_RES
set_location_assignment PIN_D6   -to  AD2_CS
set_location_assignment PIN_C6   -to  AD2_RD
set_location_assignment PIN_D7   -to  AD2_CONV
set_location_assignment PIN_F7   -to  OS2_0
set_location_assignment PIN_E7   -to  OS2_1
set_location_assignment PIN_C7   -to  OS2_2
set_location_assignment PIN_E5   -to  AD_D[0]
set_location_assignment PIN_F1   -to  AD_D[1]
set_location_assignment PIN_E1   -to  AD_D[2]
set_location_assignment PIN_C1   -to  AD_D[3]
set_location_assignment PIN_B1   -to  AD_D[4]
set_location_assignment PIN_B2   -to  AD_D[5]
set_location_assignment PIN_A3   -to  AD_D[6]
set_location_assignment PIN_B3   -to  AD_D[7]
set_location_assignment PIN_A4   -to  AD_D[8]
set_location_assignment PIN_B4   -to  AD_D[9]
set_location_assignment PIN_A5   -to  AD_D[10]
set_location_assignment PIN_B5   -to  AD_D[11]
set_location_assignment PIN_A6   -to  AD_D[12]
set_location_assignment PIN_B6   -to  AD_D[13]
set_location_assignment PIN_A7   -to  AD_D[14]
set_location_assignment PIN_B7   -to  AD_D[15]

#DSP
set_location_assignment PIN_AB9  -to   DF_D[0]
set_location_assignment PIN_AA9  -to   DF_D[1]
set_location_assignment PIN_AB10 -to   DF_D[2]
set_location_assignment PIN_AA10 -to   DF_D[3]
set_location_assignment PIN_V13  -to   DF_D[4]
set_location_assignment PIN_U12  -to   DF_D[5]
set_location_assignment PIN_V12  -to   DF_D[6]
set_location_assignment PIN_U11  -to   DF_D[7]
set_location_assignment PIN_V11  -to   DF_D[8]
set_location_assignment PIN_Y10  -to   DF_D[9]
set_location_assignment PIN_W10  -to   DF_D[10]
set_location_assignment PIN_V10  -to   DF_D[11]
set_location_assignment PIN_V9   -to   DF_D[12]
set_location_assignment PIN_U9   -to   DF_D[13]
set_location_assignment PIN_W8   -to   DF_D[14]
set_location_assignment PIN_Y8   -to   DF_D[15]
set_location_assignment PIN_AB6  -to   DF_A[0]
set_location_assignment PIN_AA5  -to   DF_A[1]
set_location_assignment PIN_AB5  -to   DF_A[2]
set_location_assignment PIN_AA4  -to   DF_A[3]
set_location_assignment PIN_AB4  -to   DF_A[4]
set_location_assignment PIN_AA3  -to   DF_A[5]
set_location_assignment PIN_AB3  -to   DF_A[6]
set_location_assignment PIN_V8   -to   DF_A[7]
set_location_assignment PIN_W7   -to   DF_A[8]
set_location_assignment PIN_Y7   -to   DF_A[9]
set_location_assignment PIN_Y6   -to   DF_A[10]
set_location_assignment PIN_W6   -to   DF_A[11]
set_location_assignment PIN_V5   -to   DF_A[12]
set_location_assignment PIN_Y3   -to   DF_A[13]
set_location_assignment PIN_T5   -to   DF_A[14]
set_location_assignment PIN_Y4   -to   DF_A[15]
set_location_assignment PIN_AA1  -to   DF_IO1
set_location_assignment PIN_Y2   -to   DF_IO2
set_location_assignment PIN_Y1   -to   DF_IO3
set_location_assignment PIN_W2   -to   DF_IO4
set_location_assignment PIN_W1   -to   DF_IO5
set_location_assignment PIN_V2   -to   DF_IO6
set_location_assignment PIN_V1   -to   DF_IO7
set_location_assignment PIN_U2   -to   DF_IO8
set_location_assignment PIN_U1   -to   DF_IO9
set_location_assignment PIN_R2   -to   DF_IO10
set_location_assignment PIN_R1   -to   DF_IO11
set_location_assignment PIN_P2   -to   DF_IO12
set_location_assignment PIN_AA8  -to   DF_XWE
set_location_assignment PIN_AB7  -to   DF_XRD
set_location_assignment PIN_AA6  -to   DF_CSRAM
set_location_assignment PIN_AA7  -to   DF_CSFPGA1
set_location_assignment PIN_AB8  -to   DF_CSFPGA2

#GX
set_location_assignment PIN_G5   -to    F_RD
set_location_assignment PIN_H3   -to    F_TD
set_location_assignment PIN_H2   -to    F_PA
set_location_assignment PIN_H1   -to    F_PB
set_location_assignment PIN_J1   -to    F_PC
set_location_assignment PIN_J2   -to    F_PD

set_location_assignment PIN_AB13	-to   FIO1
set_location_assignment PIN_Y13	-to	FIO2
set_location_assignment PIN_W13	-to	FIO3
set_location_assignment PIN_AA13	-to	FIO4
set_location_assignment PIN_V14	-to	FIO5
set_location_assignment PIN_AB14	-to	FIO6
set_location_assignment PIN_W14	-to	FIO7
set_location_assignment PIN_Y14	-to	FIO8
set_location_assignment PIN_AA14	-to	FIO9
set_location_assignment PIN_W15	-to	FIO10
set_location_assignment PIN_V15	-to	FIO11
set_location_assignment PIN_AB15	-to	FIO12
set_location_assignment PIN_AA15	-to	FIO13
set_location_assignment PIN_AB16	-to	FIO14
set_location_assignment PIN_Y15	-to	FIO15
set_location_assignment PIN_T16	-to	FIO16
set_location_assignment PIN_AA16	-to	FIO17
set_location_assignment PIN_T15	-to	FIO18
set_location_assignment PIN_V16	-to   FIO19
set_location_assignment PIN_AB17	-to	FIO20
set_location_assignment PIN_AA17	-to	FIO21
set_location_assignment PIN_AB18	-to	FIO22
set_location_assignment PIN_W17  -to  	FIO23
set_location_assignment PIN_AB19	-to	FIO24

set_location_assignment PIN_AB20	-to	FIO25
set_location_assignment PIN_AA18	-to	FIO26
set_location_assignment PIN_Y17  -to   FIO27
set_location_assignment PIN_AA21	-to	FIO28
set_location_assignment PIN_T17 	-to	FIO29
set_location_assignment PIN_Y22	-to	FIO30
set_location_assignment PIN_T18	-to	FIO31
set_location_assignment PIN_W21 	-to   FIO32
set_location_assignment PIN_W22 	-to   FIO33
set_location_assignment PIN_AA19	-to	FIO34
set_location_assignment PIN_AA20	-to	FIO35
set_location_assignment PIN_V21	-to	FIO36
set_location_assignment PIN_W20	-to	FIO37
set_location_assignment PIN_V22 	-to   FIO38
set_location_assignment PIN_W19	-to	FIO39
set_location_assignment PIN_U20	-to	FIO40
set_location_assignment PIN_U21	-to	FIO41
set_location_assignment PIN_T19	-to	FIO42
set_location_assignment PIN_T20 	-to   FIO43
set_location_assignment PIN_U22	-to	FIO44
set_location_assignment PIN_R17	-to	FIO45
set_location_assignment PIN_R21	-to	FIO46
set_location_assignment PIN_R16	-to	FIO47
set_location_assignment PIN_R20 	-to   FIO48

set_location_assignment PIN_R22	-to	FIO49
set_location_assignment PIN_R19	-to	FIO50
set_location_assignment PIN_P20	-to	FIO51
set_location_assignment PIN_P21	-to	FIO52
set_location_assignment PIN_N18 	-to   FIO53
set_location_assignment PIN_P22	-to	FIO54
set_location_assignment PIN_N19	-to	FIO55
set_location_assignment PIN_N20 	-to   FIO56
set_location_assignment PIN_N21	-to	FIO57
set_location_assignment PIN_M16	-to	FIO58
set_location_assignment PIN_M19 	-to   FIO59
set_location_assignment PIN_N22	-to	FIO60
set_location_assignment PIN_M20	-to	FIO61
set_location_assignment PIN_M21	-to	FIO62
set_location_assignment PIN_K18	-to	FIO63
set_location_assignment PIN_K19	-to	FIO64
set_location_assignment PIN_M22	-to	FIO65
set_location_assignment PIN_J18	-to	FIO66
set_location_assignment PIN_J20	-to	FIO67
set_location_assignment PIN_L21	-to	FIO68
set_location_assignment PIN_H18	-to	FIO69
set_location_assignment PIN_L22	-to	FIO70
set_location_assignment PIN_H19	-to	FIO71
set_location_assignment PIN_H20	-to	FIO72

set_location_assignment PIN_K21	-to	FIO73
set_location_assignment PIN_G18	-to	FIO74
set_location_assignment PIN_F15	-to	FIO75
set_location_assignment PIN_K22	-to	FIO76
set_location_assignment PIN_F17	-to	FIO77
set_location_assignment PIN_J21	-to	FIO78
set_location_assignment PIN_F20	-to	FIO79
set_location_assignment PIN_F19	-to	FIO80
set_location_assignment PIN_J22	-to	FIO81
set_location_assignment PIN_H21	-to	FIO82
set_location_assignment PIN_E15	-to	FIO83
set_location_assignment PIN_H22	-to	FIO84
set_location_assignment PIN_F21	-to	FIO85
set_location_assignment PIN_E22	-to	FIO86
set_location_assignment PIN_E21	-to	FIO87
set_location_assignment PIN_F22	-to	FIO88
set_location_assignment PIN_D21	-to	FIO89
set_location_assignment PIN_E16	-to	FIO90
set_location_assignment PIN_D22	-to	FIO91
set_location_assignment PIN_D20	-to	FIO92
set_location_assignment PIN_D17	-to	FIO93
set_location_assignment PIN_C22	-to	FIO94
set_location_assignment PIN_D18	-to	FIO95
set_location_assignment PIN_C21	-to	FIO96

set_location_assignment PIN_B21	-to	FIO97
set_location_assignment PIN_D19	-to	FIO98
set_location_assignment PIN_B22	-to	FIO99
set_location_assignment PIN_C19	-to	FIO100
set_location_assignment PIN_C20	-to	FIO101
set_location_assignment PIN_A20	-to	FIO102
set_location_assignment PIN_B20	-to	FIO103
set_location_assignment PIN_C18	-to	FIO104
set_location_assignment PIN_A19	-to	FIO105
set_location_assignment PIN_B19	-to	FIO106
set_location_assignment PIN_A18	-to	FIO107
set_location_assignment PIN_C17	-to	FIO108
set_location_assignment PIN_B18	-to	FIO109
set_location_assignment PIN_A17	-to	FIO110
set_location_assignment PIN_B16	-to	FIO111
set_location_assignment PIN_B17	-to	FIO112
set_location_assignment PIN_A15	-to	FIO113
set_location_assignment PIN_A16	-to	FIO114
set_location_assignment PIN_B14	-to	FIO115
set_location_assignment PIN_C15	-to	FIO116
set_location_assignment PIN_D15	-to	FIO117
set_location_assignment PIN_A14	-to	FIO118
set_location_assignment PIN_F14 	-to   FIO119
set_location_assignment PIN_B15 	-to   FIO120

set_location_assignment PIN_B13	-to	FIO121
set_location_assignment PIN_E14 	-to   FIO122
set_location_assignment PIN_B10	-to	FIO123
set_location_assignment PIN_F13	-to	FIO124
set_location_assignment PIN_A13 	-to   FIO125
set_location_assignment PIN_A10	-to	FIO126
set_location_assignment PIN_C13	-to	FIO127
set_location_assignment PIN_E13	-to	FIO128
set_location_assignment PIN_F11	-to	FIO129
set_location_assignment PIN_D13 	-to   FIO130
set_location_assignment PIN_E11	-to	FIO131
set_location_assignment PIN_F10	-to	FIO132
set_location_assignment PIN_E12	-to	FIO133
set_location_assignment PIN_B9 	-to	FIO134
set_location_assignment PIN_C10	-to	FIO135
set_location_assignment PIN_D10 	-to   FIO136
set_location_assignment PIN_A9	-to	FIO137
set_location_assignment PIN_F9	-to	FIO138
set_location_assignment PIN_B8 	-to   FIO139
set_location_assignment PIN_E8	-to   FIO140
set_location_assignment PIN_E9 	-to   FIO141
set_location_assignment PIN_A8 	-to   FIO142
set_location_assignment PIN_C8	-to   FIO143
set_location_assignment PIN_D8 	-to   FIO144